// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLBz6F-30p62ciP3bBvHZKZxi7-HjoWWc',
    appId: '1:687401498519:web:cf09955bab8572a39d76d2',
    messagingSenderId: '687401498519',
    projectId: 'gestion-6650e',
    authDomain: 'gestion-6650e.firebaseapp.com',
    storageBucket: 'gestion-6650e.firebasestorage.app',
    measurementId: 'G-KLZEER94XN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsT5GQE7zzMkxaCKQiCsBdioKAjMLF90Y',
    appId: '1:687401498519:android:49e0f7ca106b770c9d76d2',
    messagingSenderId: '687401498519',
    projectId: 'gestion-6650e',
    storageBucket: 'gestion-6650e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvcakk61y4I18uamwBSeLGDAtXuGuU2YE',
    appId: '1:687401498519:ios:c2dfbba5f0409af79d76d2',
    messagingSenderId: '687401498519',
    projectId: 'gestion-6650e',
    storageBucket: 'gestion-6650e.firebasestorage.app',
    iosBundleId: 'com.example.gestionGastos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvcakk61y4I18uamwBSeLGDAtXuGuU2YE',
    appId: '1:687401498519:ios:c2dfbba5f0409af79d76d2',
    messagingSenderId: '687401498519',
    projectId: 'gestion-6650e',
    storageBucket: 'gestion-6650e.firebasestorage.app',
    iosBundleId: 'com.example.gestionGastos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLBz6F-30p62ciP3bBvHZKZxi7-HjoWWc',
    appId: '1:687401498519:web:fa0a9aeb1558ff769d76d2',
    messagingSenderId: '687401498519',
    projectId: 'gestion-6650e',
    authDomain: 'gestion-6650e.firebaseapp.com',
    storageBucket: 'gestion-6650e.firebasestorage.app',
    measurementId: 'G-ZK8K4Q8WGY',
  );
}
